d1a69509321e8d9f-Traceback (most recent call last):
  File "C:/Users/YQ/Desktop/小满海关数据爬取/step1.py", line 52, in get_data
    response = self.session.post(url=self.url1, data=params, proxies={'http': proxy}).json()
  File "D:\Anaconda\lib\site-packages\requests\models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "D:\Anaconda\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "D:\Anaconda\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Anaconda\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step2.py", line 116, in get_data
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step2.py", line 245, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 's offers the largest selection of living room, bedroom and dining sets to handma' at line 1")
&c7190323ccc64502-Traceback (most recent call last):
  File "C:/Users/YQ/Desktop/小满海关数据爬取/step1.py", line 52, in get_data
    response = self.session.post(url=self.url1, data=params, proxies={'http': proxy}).json()
  File "D:\Anaconda\lib\site-packages\requests\models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "D:\Anaconda\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "D:\Anaconda\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Anaconda\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step2.py", line 116, in get_data
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step2.py", line 245, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'Connor's Carpet One Floor & Home in Saginaw offers one of the largest selections' at line 1")
&2567240c38e15e61-Traceback (most recent call last):
  File "C:/Users/YQ/Desktop/小满海关数据爬取/step1.py", line 52, in get_data
    response = self.session.post(url=self.url1, data=params, proxies={'http': proxy}).json()
  File "D:\Anaconda\lib\site-packages\requests\models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "D:\Anaconda\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "D:\Anaconda\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Anaconda\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step2.py", line 116, in get_data
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step2.py", line 245, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 's Largest Supplier of Amateur Radio, Ham Radio, and Communication Equipment. Sal' at line 1")
&