b835b5976024ed4e-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step2.py", line 104, in get_data
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step2.py", line 234, in write2sql
    cur1.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 515, in query
    self._execute_command(COMMAND.COM_QUERY, sql)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 745, in _execute_command
    raise err.InterfaceError("(0, '')")
pymysql.err.InterfaceError: (0, '')
&3954cb901ffa8b70-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step2.py", line 104, in get_data
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step2.py", line 234, in write2sql
    cur1.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 515, in query
    self._execute_command(COMMAND.COM_QUERY, sql)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 745, in _execute_command
    raise err.InterfaceError("(0, '')")
pymysql.err.InterfaceError: (0, '')
&019859d24e05e099-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step2.py", line 104, in get_data
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step2.py", line 234, in write2sql
    cur1.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 515, in query
    self._execute_command(COMMAND.COM_QUERY, sql)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 745, in _execute_command
    raise err.InterfaceError("(0, '')")
pymysql.err.InterfaceError: (0, '')
&eac460af1efdb2be-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step2.py", line 104, in get_data
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step2.py", line 234, in write2sql
    cur1.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 515, in query
    self._execute_command(COMMAND.COM_QUERY, sql)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 745, in _execute_command
    raise err.InterfaceError("(0, '')")
pymysql.err.InterfaceError: (0, '')
&5bebb6e63d3bebc1-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step2.py", line 104, in get_data
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step2.py", line 234, in write2sql
    cur1.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 515, in query
    self._execute_command(COMMAND.COM_QUERY, sql)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 745, in _execute_command
    raise err.InterfaceError("(0, '')")
pymysql.err.InterfaceError: (0, '')
&51d934fa73be94c1-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step2.py", line 104, in get_data
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step2.py", line 234, in write2sql
    cur1.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 515, in query
    self._execute_command(COMMAND.COM_QUERY, sql)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 745, in _execute_command
    raise err.InterfaceError("(0, '')")
pymysql.err.InterfaceError: (0, '')
&13bbb7e056e428e0-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step2.py", line 104, in get_data
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step2.py", line 234, in write2sql
    cur1.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 515, in query
    self._execute_command(COMMAND.COM_QUERY, sql)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 745, in _execute_command
    raise err.InterfaceError("(0, '')")
pymysql.err.InterfaceError: (0, '')
&f64a555bbe2cd3a8-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step2.py", line 104, in get_data
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step2.py", line 234, in write2sql
    cur1.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 515, in query
    self._execute_command(COMMAND.COM_QUERY, sql)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 745, in _execute_command
    raise err.InterfaceError("(0, '')")
pymysql.err.InterfaceError: (0, '')
&d6b8db91a77fac04-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step2.py", line 104, in get_data
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step2.py", line 234, in write2sql
    cur1.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 515, in query
    self._execute_command(COMMAND.COM_QUERY, sql)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 745, in _execute_command
    raise err.InterfaceError("(0, '')")
pymysql.err.InterfaceError: (0, '')
&2c279379899e1364-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step2.py", line 104, in get_data
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step2.py", line 234, in write2sql
    cur1.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 515, in query
    self._execute_command(COMMAND.COM_QUERY, sql)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 745, in _execute_command
    raise err.InterfaceError("(0, '')")
pymysql.err.InterfaceError: (0, '')
&3da9fb8fc92ce6d1-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step2.py", line 104, in get_data
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step2.py", line 234, in write2sql
    cur1.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 515, in query
    self._execute_command(COMMAND.COM_QUERY, sql)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 745, in _execute_command
    raise err.InterfaceError("(0, '')")
pymysql.err.InterfaceError: (0, '')
&7aeab7b15fb256a4-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step2.py", line 104, in get_data
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step2.py", line 234, in write2sql
    cur1.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 515, in query
    self._execute_command(COMMAND.COM_QUERY, sql)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 745, in _execute_command
    raise err.InterfaceError("(0, '')")
pymysql.err.InterfaceError: (0, '')
&b9df26c9f4b17af8-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step2.py", line 104, in get_data
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step2.py", line 234, in write2sql
    cur1.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 515, in query
    self._execute_command(COMMAND.COM_QUERY, sql)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 745, in _execute_command
    raise err.InterfaceError("(0, '')")
pymysql.err.InterfaceError: (0, '')
&ae47a4a8c03ea7be-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step2.py", line 104, in get_data
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step2.py", line 234, in write2sql
    cur1.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 515, in query
    self._execute_command(COMMAND.COM_QUERY, sql)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 745, in _execute_command
    raise err.InterfaceError("(0, '')")
pymysql.err.InterfaceError: (0, '')
&8d7f58994597ea2b-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step2.py", line 104, in get_data
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step2.py", line 234, in write2sql
    cur1.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 515, in query
    self._execute_command(COMMAND.COM_QUERY, sql)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 745, in _execute_command
    raise err.InterfaceError("(0, '')")
pymysql.err.InterfaceError: (0, '')
&9a6691ec2b0f205e-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step2.py", line 104, in get_data
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step2.py", line 234, in write2sql
    cur1.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 515, in query
    self._execute_command(COMMAND.COM_QUERY, sql)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 745, in _execute_command
    raise err.InterfaceError("(0, '')")
pymysql.err.InterfaceError: (0, '')
&24455694f3d9c9a7-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step2.py", line 104, in get_data
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step2.py", line 234, in write2sql
    cur1.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 515, in query
    self._execute_command(COMMAND.COM_QUERY, sql)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 745, in _execute_command
    raise err.InterfaceError("(0, '')")
pymysql.err.InterfaceError: (0, '')
&e6e8db40eb77a180-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step2.py", line 104, in get_data
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step2.py", line 234, in write2sql
    cur1.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 515, in query
    self._execute_command(COMMAND.COM_QUERY, sql)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 745, in _execute_command
    raise err.InterfaceError("(0, '')")
pymysql.err.InterfaceError: (0, '')
&383c2062aa3870ee-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step2.py", line 104, in get_data
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step2.py", line 234, in write2sql
    cur1.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 515, in query
    self._execute_command(COMMAND.COM_QUERY, sql)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 745, in _execute_command
    raise err.InterfaceError("(0, '')")
pymysql.err.InterfaceError: (0, '')
&a7fb897a3fe5a600-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step2.py", line 104, in get_data
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step2.py", line 234, in write2sql
    cur1.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 515, in query
    self._execute_command(COMMAND.COM_QUERY, sql)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 745, in _execute_command
    raise err.InterfaceError("(0, '')")
pymysql.err.InterfaceError: (0, '')
&ad5484ec60f69812-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step2.py", line 104, in get_data
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step2.py", line 234, in write2sql
    cur1.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 515, in query
    self._execute_command(COMMAND.COM_QUERY, sql)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 745, in _execute_command
    raise err.InterfaceError("(0, '')")
pymysql.err.InterfaceError: (0, '')
&47c4105c5258618e-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step2.py", line 104, in get_data
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step2.py", line 234, in write2sql
    cur1.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 515, in query
    self._execute_command(COMMAND.COM_QUERY, sql)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 745, in _execute_command
    raise err.InterfaceError("(0, '')")
pymysql.err.InterfaceError: (0, '')
&16f04f479abf9d0e-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step2.py", line 104, in get_data
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step2.py", line 234, in write2sql
    cur1.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 515, in query
    self._execute_command(COMMAND.COM_QUERY, sql)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 745, in _execute_command
    raise err.InterfaceError("(0, '')")
pymysql.err.InterfaceError: (0, '')
&75267ce3e82ced62-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step2.py", line 104, in get_data
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step2.py", line 234, in write2sql
    cur1.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 515, in query
    self._execute_command(COMMAND.COM_QUERY, sql)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 745, in _execute_command
    raise err.InterfaceError("(0, '')")
pymysql.err.InterfaceError: (0, '')
&8f06cc22ae66f415-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step2.py", line 104, in get_data
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step2.py", line 234, in write2sql
    cur1.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 515, in query
    self._execute_command(COMMAND.COM_QUERY, sql)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 745, in _execute_command
    raise err.InterfaceError("(0, '')")
pymysql.err.InterfaceError: (0, '')
&