Paraguay2018V212f45d79ab02d66eb875d6c5532a4fef-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'CANADA','TER. DE CARGAS KM.12', 'None','N' at line 1")
&Paraguay2018V2bd34a51073b3298a90d085b5c58e5055-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'CANADA','TER. DE CARGAS KM.12', 'None','N' at line 1")
&Paraguay2018V276dccd583dd1b5af89e39af6b7768ebc-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'CANADA','TER. DE CARGAS KM.12', 'None','N' at line 1")
&Paraguay2018V2f7056c2db2cdc5631edf97d6e98a2941-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'CANADA','TER. DE CARGAS KM.12', 'None','N' at line 1")
&Paraguay2018V2395d6835651a530c28fb929d63627a0c-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'CANADA','TER. DE CARGAS KM.12', 'None','N' at line 1")
&Paraguay2018V279533f269fa539b3f7c66ff097a0fe0e-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'CANADA','TER. DE CARGAS KM.12', 'None','N' at line 1")
&Paraguay2018V2aeb17509b9da24072ce1581a826fa7e6-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'CANADA','TER. DE CARGAS KM.12', 'None','N' at line 1")
&Paraguay2018V21ec89561ebb3ab7336cdadc46c9f8780-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'CANADA','TER. DE CARGAS KM.12', 'None','N' at line 1")
&Paraguay2018V20118b03dd1cca061f34c122745f9534e-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'CANADA','TER. DE CARGAS KM.12', 'None','N' at line 1")
&Paraguay2018V2059f63f4bce5fdb6c6d2faf55b15ad38-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'CANADA','TER. DE CARGAS KM.12', 'None','N' at line 1")
&Paraguay2018V2b015f70642a7bb53af4d77981a8d0dd0-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'CANADA','TER. DE CARGAS KM.12', 'None','N' at line 1")
&Paraguay2018V2ec9be6489c8510a94d946ee877e4ef02-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'CANADA','TER. DE CARGAS KM.12', 'None','N' at line 1")
&Paraguay2018V20516ad27c91d87495b3e30f656b99645-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'CANADA','TER. DE CARGAS KM.12', 'None','N' at line 1")
&Paraguay2018V26ebf4d28ec3fbb03cd1b3b64233dc6d2-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'CANADA','TER. DE CARGAS KM.12', 'None','N' at line 1")
&Paraguay2018V22daf58e16989f258637a62ca1309558c-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'CANADA','TER. DE CARGAS KM.12', 'None','N' at line 1")
&Paraguay201707086009fd780ce5efee97a72fe52687-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'CANADA','TER. DE CARGAS KM.12', 'None','N' at line 1")
&Paraguay2017dc1ffd73812a90a9cc1a96140c8024c4-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'CANADA','TER. DE CARGAS KM.12', 'None','N' at line 1")
&Paraguay20174cfa438ea903ceb4bd2677002a544c23-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'CANADA','TER. DE CARGAS KM.12', 'None','N' at line 1")
&432cae1f3fa7ce7e-134-EXPORT-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 116, in get_data
    self.get_data1(i['id'], hashid)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 129, in get_data1
    user, proxy, cookies = get_cookie()
  File "C:\Users\YQ\Desktop\小满海关数据爬取\Util\tools.py", line 139, in get_cookie
    user, proxy, cookies_ = cookies()
  File "C:\Users\YQ\Desktop\小满海关数据爬取\Util\tools.py", line 99, in cookies
    update_cookies()
  File "C:\Users\YQ\Desktop\小满海关数据爬取\Util\tools.py", line 74, in update_cookies
    users[params[0]]['proxy'], users[params[0]]['cookies'] = login(params[0], params[1])
  File "C:\Users\YQ\Desktop\小满海关数据爬取\login1.py", line 81, in login
    return sp.get_login(user, pwd)   #返回cookies
  File "C:\Users\YQ\Desktop\小满海关数据爬取\login1.py", line 69, in get_login
    return self.get_login(user, pwd)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\login1.py", line 24, in get_login
    self.web.get('https://login.xiaoman.cn/login?system_id=discovery&return_url=https%3A%2F%2Fx.xiaoman.cn%2F')
  File "D:\Anaconda\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 332, in get
    self.execute(Command.GET, {'url': url})
  File "D:\Anaconda\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "D:\Anaconda\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: no such session
  (Driver info: chromedriver=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab),platform=Windows NT 10.0.17134 x86_64)

&Paraguay2015d72bcacd8573d2ac8f188d3c8917907b-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'ITALIA','ENCARNACION', 'None','None', now' at line 1")
&Paraguay2015cf90dafe95f08a3025ed65a9d26ecbb1-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'CANADA','ENCARNACION', 'None','None', now' at line 1")
&Paraguay2015f2f8e4059985483f53ffd0d7452f644b-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'CHINA','ENCARNACION', 'None','None', now(' at line 1")
&Paraguay201595ff85dcadad72642b2559cb30e17892-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'ESTADOS UNIDOS','ENCARNACION', 'None','No' at line 1")
&Paraguay2015775f0e81fb44c72e31669a6409b6fa36-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'CANADA','ENCARNACION', 'None','None', now' at line 1")
&Paraguay20158affd1eec22fdc8efd058d3d97adfdd2-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'CHINA','ENCARNACION', 'None','None', now(' at line 1")
&Paraguay2015b27458024af27d3b28d7b6b31292d7df-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'CHINA','ENCARNACION', 'None','None', now(' at line 1")
&Paraguay201535d7b6068d4db8d573eef66e3c08030c-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'CANADA','ENCARNACION', 'None','None', now' at line 1")
&Paraguay201509e384d93c1297f569c3545203d7b89a-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'POLONIA','ENCARNACION', 'None','None', no' at line 1")
&Paraguay2015f6d578dc5164f52ffd874556779b4450-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'ESTADOS UNIDOS','ENCARNACION', 'None','No' at line 1")
&Paraguay2015fabcba2b9771a9eec7c4357d4d5520da-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'ITALIA','ENCARNACION', 'None','None', now' at line 1")
&Paraguay20158cb687e7bff73d8ce8f84d9707312d1b-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'CANADA','ENCARNACION', 'None','None', now' at line 1")
&Paraguay20156a8073aaca02d69bf62f0107547f6eb9-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'CANADA','ENCARNACION', 'None','None', now' at line 1")
&Paraguay20159ec47030c9a32262affc106baa470ce4-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'CANADA','ENCARNACION', 'None','None', now' at line 1")
&Paraguay20157cd1e9b20c19cd04a438256fa29047a0-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'ITALIA','ENCARNACION', 'None','None', now' at line 1")
&Paraguay201507291ea712ab1dd6063bd7081be63b12-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'CANADA','ENCARNACION', 'None','None', now' at line 1")
&Paraguay201540797378dcc393bc01838f54ffbeb174-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'ESTADOS UNIDOS','ENCARNACION', 'None','No' at line 1")
&Paraguay201532bdb87519fc8995e4a20e16276378a5-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'ESTADOS UNIDOS','ENCARNACION', 'None','No' at line 1")
&Paraguay20157f35414e21c5dbbc2d75af6dad8d24f2-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'ESTADOS UNIDOS','ENCARNACION', 'None','No' at line 1")
&Paraguay20151bacf422d0031a5ca2bf0f95f7e0c53f-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'CANADA','ENCARNACION', 'None','None', now' at line 1")
&Paraguay20151dbc87c59e11ede64ffd9e284dabdf03-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'ITALIA','ENCARNACION', 'None','None', now' at line 1")
&Paraguay20158ce08c2975d55cbcc949a82d6f0b84a3-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'JAPON','ENCARNACION', 'None','None', now(' at line 1")
&Paraguay201578f7695815b519fb63e11bdca74cee98-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'ITALIA','ENCARNACION', 'None','None', now' at line 1")
&Paraguay20157107c99f2b0a68704cc1f549f96ea927-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'ITALIA','ENCARNACION', 'None','None', now' at line 1")
&Paraguay20150412098800f292ed5ddfab404b5411ab-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'TAIWAN','ENCARNACION', 'None','None', now' at line 1")
&Paraguay2015490a86f813d40f35f85890ca3b02c936-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'ITALIA','ENCARNACION', 'None','None', now' at line 1")
&Paraguay201588f8928269876fdce9cb136178b5964f-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'JAPON','ENCARNACION', 'None','None', now(' at line 1")
&Paraguay20157ddc52a551b86c116582324160e1f83b-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'ESTADOS UNIDOS','ENCARNACION', 'None','No' at line 1")
&Paraguay20155b666116f33eb451662db7c125538ee9-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'CANADA','ENCARNACION', 'None','None', now' at line 1")
&Paraguay201569172dcd69d7b47483317ff759a59477-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'CHINA','ENCARNACION', 'None','None', now(' at line 1")
&Paraguay2015b835b8a5274ab431150f0f3dfbabf04d-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'ITALIA','ENCARNACION', 'None','None', now' at line 1")
&Paraguay2015adcef78060455ce57d3804dfb7a2f58e-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'ESTADOS UNIDOS','ENCARNACION', 'None','No' at line 1")
&Paraguay2015203a3e5589db5a4feef389c2a864a4fb-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'CANADA','ENCARNACION', 'None','None', now' at line 1")
&Paraguay2015f7dd10527bc66036046d5e9999a2f2a8-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'CANADA','ENCARNACION', 'None','None', now' at line 1")
&Paraguay201568a4c0a4aac0a4d99d2562ffa16e31fe-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'CANADA','ENCARNACION', 'None','None', now' at line 1")
&Paraguay20159d604fe88a3c943112556c9c5287efd4-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'TAIWAN','ENCARNACION', 'None','None', now' at line 1")
&Paraguay20157c6f9799e247ebec3a1a42bc409526fa-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'ESTADOS UNIDOS','ENCARNACION', 'None','No' at line 1")
&Paraguay2015099f3aa09c5a57a686ce4e40926ef591-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'CANADA','ENCARNACION', 'None','None', now' at line 1")
&Paraguay2015eb04e94883bd1dc260a77ea9cc766816-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'ESTADOS UNIDOS','ENCARNACION', 'None','No' at line 1")
&Paraguay2015291f6a0a5d8a0e648dc08dfdeea78dd7-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'ESTADOS UNIDOS','ENCARNACION', 'None','No' at line 1")
&Paraguay201564407aee555753eca77fc87bdf2cc6c4-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'CHINA','ENCARNACION', 'None','None', now(' at line 1")
&Paraguay2015c087457908cbcea403d081e8e0a925b2-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'CANADA','ENCARNACION', 'None','None', now' at line 1")
&Paraguay201502b35ed6aa3d2827246ea1b4dc7044a5-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'ESTADOS UNIDOS','ENCARNACION', 'None','No' at line 1")
&Paraguay20157f6509d8c8d1ea72c8d874d742c0dc89-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'ESTADOS UNIDOS','ENCARNACION', 'None','No' at line 1")
&Paraguay2015ca8f41ebe2daf6e998b8a0c76082ad3a-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'ESTADOS UNIDOS','ENCARNACION', 'None','No' at line 1")
&Paraguay2015d94c4bdfdb606f81efc07ef90fe53e72-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'ITALIA','ENCARNACION', 'None','None', now' at line 1")
&Paraguay2015b686928903e0ebdc3cd2d3d0384d59f8-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'ALEMANIA','ENCARNACION', 'None','None', n' at line 1")
&Paraguay20152aeaccd0d3eed8b4afbe120b05aff50f-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'ALEMANIA','ENCARNACION', 'None','None', n' at line 1")
&Paraguay2015d2b507f1337bdf0a991cb3bdeb140bdf-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'CHINA','ENCARNACION', 'None','None', now(' at line 1")
&Paraguay2015eef9f447bf68dca0f21ce4b008c6fdb1-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'CANADA','ENCARNACION', 'None','None', now' at line 1")
&Paraguay2015eb889ec0a6c0f5a3acb433b365f385d7-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'TAIWAN','ENCARNACION', 'None','None', now' at line 1")
&Paraguay201585bddbfc3b8b624b3a755dd6c622de53-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'CHINA','ENCARNACION', 'None','None', now(' at line 1")
&Paraguay201583f5b7f49a2dbcd848585ca7af28a7bd-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'ESTADOS UNIDOS','ENCARNACION', 'None','No' at line 1")
&Paraguay2015c89ca5173857016a51a472e42a10d82d-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'ESTADOS UNIDOS','ENCARNACION', 'None','No' at line 1")
&Paraguay2015c340c64cab2b4d63da25a807e6fcda32-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'ESTADOS UNIDOS','ENCARNACION', 'None','No' at line 1")
&Paraguay201541b302bfb6ab63e6a541c628c4d9dc36-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'CANADA','ENCARNACION', 'None','None', now' at line 1")
&Paraguay20153e53bf0b578aeed9dca0d3704fad34ca-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'ALEMANIA','ENCARNACION', 'None','None', n' at line 1")
&Paraguay2015e1748ee3695b75883bfb21ffb422fdad-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'CANADA','ENCARNACION', 'None','None', now' at line 1")
&Paraguay201506569f264a68d8f0dd2143346e447565-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'CANADA','ENCARNACION', 'None','None', now' at line 1")
&Paraguay201539f6c7f1bfc74679544832fadf0990bf-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'ESTADOS UNIDOS','ENCARNACION', 'None','No' at line 1")
&Paraguay2015419b82e16001e86cfb01c4c0da2dbb53-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'JAPON','ENCARNACION', 'None','None', now(' at line 1")
&Paraguay2015aa3ca68b510fd6821c92277095e5e3d4-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'CHINA','ENCARNACION', 'None','None', now(' at line 1")
&Paraguay2015c19d5e980dc8c1365559b3388794d9de-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'CANADA','ENCARNACION', 'None','None', now' at line 1")
&Paraguay2015c1d62555067f3e180f74ee82ecdd9bbd-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'CANADA','ENCARNACION', 'None','None', now' at line 1")
&Paraguay20154d34ee62bbe552d4e8f9b058c0d78fbe-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'CHINA','ENCARNACION', 'None','None', now(' at line 1")
&Paraguay2015498ca4f30282140be008278a5f00591b-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'POLONIA','ENCARNACION', 'None','None', no' at line 1")
&Paraguay2015ec03383730789ae97e15a4dbc9b11d7e-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'CANADA','ENCARNACION', 'None','None', now' at line 1")
&Paraguay201585e2db6f24c18b4f75e25c4fad4888dc-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'ESTADOS UNIDOS','ENCARNACION', 'None','No' at line 1")
&Paraguay20157f4ec8028895c88cd0f16337853e20a2-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'ESTADOS UNIDOS','ENCARNACION', 'None','No' at line 1")
&Paraguay2015aec9e74b01a96d3d2dd3b0c8c02ed6e4-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'ESTADOS UNIDOS','ENCARNACION', 'None','No' at line 1")
&Paraguay2015d96e013552cbbaadac5f3d0b534f9c54-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'ESTADOS UNIDOS','ENCARNACION', 'None','No' at line 1")
&Paraguay201591114710e29c1a7b99895bedfb89befd-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'JAPON','ENCARNACION', 'None','None', now(' at line 1")
&Paraguay201528c8d9b2990ff95d982bca19db161a2d-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'ESTADOS UNIDOS','ENCARNACION', 'None','No' at line 1")
&Paraguay20155e2b06c9c609528c30f23f0f71992c50-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'ESTADOS UNIDOS','ENCARNACION', 'None','No' at line 1")
&Paraguay2015157909e991ea7895c738a98599cecae9-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'CANADA','ENCARNACION', 'None','None', now' at line 1")
&Paraguay201519f0516fc35284589248cc58cff305e0-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'POLONIA','ENCARNACION', 'None','None', no' at line 1")
&Paraguay2015d793ce1bbf4a081f6464a3d01a4e283f-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'CANADA','ENCARNACION', 'None','None', now' at line 1")
&Paraguay201512b8a8196d9fdfc9dfd69b9d915a4db9-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'ESTADOS UNIDOS','ENCARNACION', 'None','No' at line 1")
&Paraguay201511714f4559b76638744dc25f2e61aedd-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'TAIWAN','ENCARNACION', 'None','None', now' at line 1")
&Paraguay20153bf2b1e39a40537e19928315417e46e2-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'ESTADOS UNIDOS','ENCARNACION', 'None','No' at line 1")
&Paraguay201561ff371c2bdf0fa8754227615ddde656-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'ESTADOS UNIDOS','ENCARNACION', 'None','No' at line 1")
&Paraguay2015fe4124ce64d1ad18381a5f4812c3f919-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'ESTADOS UNIDOS','ENCARNACION', 'None','No' at line 1")
&Paraguay2015d21ded55aa9598f20452afbb8668cbb9-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'CANADA','ENCARNACION', 'None','None', now' at line 1")
&Paraguay2015551890cf12e160f297ae31a71ff220a0-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'CANADA','ENCARNACION', 'None','None', now' at line 1")
&Paraguay201574a09771d15be6fc92c4d224657d906a-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'CANADA','ENCARNACION', 'None','None', now' at line 1")
&Paraguay201596f26c0e8ef18aea3f03dee8dbd1cc25-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'CANADA','ENCARNACION', 'None','None', now' at line 1")
&Paraguay201596cb4bcd989dd1972fe98d7c0b7b9ac5-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'CANADA','ENCARNACION', 'None','None', now' at line 1")
&Paraguay2015bc13e1fe9037520c8ee9a3de509f5a8a-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'CANADA','ENCARNACION', 'None','None', now' at line 1")
&Paraguay2015c011009350afe8ef3a6674d0cf91685c-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'CANADA','ENCARNACION', 'None','None', now' at line 1")
&Paraguay2015bbb39070680de90ee91ad20eb499b2f5-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'CANADA','ENCARNACION', 'None','None', now' at line 1")
&Paraguay20152c33ec8ce0c6db4ecab9a38470799352-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'CANADA','ENCARNACION', 'None','None', now' at line 1")
&Paraguay201508fe63ec58855ca05dddf4d082e872c6-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'CANADA','ENCARNACION', 'None','None', now' at line 1")
&Paraguay20152016ab6937af1581287a2a133df1c643-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'CANADA','ENCARNACION', 'None','None', now' at line 1")
&Paraguay2015bb8e5f9d2e1e4bfcdc4a8f2a23efe0ee-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'CANADA','ENCARNACION', 'None','None', now' at line 1")
&Paraguay20156d88aaa7a44ca96a29e7894557b110f9-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'CANADA','ENCARNACION', 'None','None', now' at line 1")
&Paraguay2015213b006abc97311dbd8b7e86b1364512-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'CANADA','ENCARNACION', 'None','None', now' at line 1")
&Paraguay2015755506216b3073287f83fe4a865ee57c-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'CANADA','ENCARNACION', 'None','None', now' at line 1")
&Paraguay201572b766e6dad420516731cc1b16986dc1-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'CANADA','ENCARNACION', 'None','None', now' at line 1")
&Paraguay2015d09dd8c804a7c78d14f4daaa2df99023-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'CANADA','ENCARNACION', 'None','None', now' at line 1")
&Paraguay2015bfd8e8ae722f73fb37544a0972cb1122-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'CANADA','ENCARNACION', 'None','None', now' at line 1")
&Paraguay201509b259b7f0de04d1ee50deec2754472d-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'CANADA','ENCARNACION', 'None','None', now' at line 1")
&Paraguay20159515ecb9e9e03ad82a3f831d42c728ca-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 203, in get_data1
    self.write2sql(sql)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 214, in write2sql
    cur.execute(sql)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Anaconda\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "D:\Anaconda\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'I  E  HI','PARAGUAY', '', '', 'None', 'CANADA','ENCARNACION', 'None','None', now' at line 1")
&9e96c77d4a541de9-7-EXPORT-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\login1.py", line 27, in get_login
    username = self.web.find_element_by_id('email')
  File "D:\Anaconda\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 359, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "D:\Anaconda\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 966, in find_element
    'value': value})['value']
  File "D:\Anaconda\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "D:\Anaconda\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"email"}
  (Session info: chrome=68.0.3440.106)
  (Driver info: chromedriver=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab),platform=Windows NT 10.0.17134 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 116, in get_data
    self.get_data1(i['id'], hashid)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 129, in get_data1
    user, proxy, cookies = get_cookie()
  File "C:\Users\YQ\Desktop\小满海关数据爬取\Util\tools.py", line 139, in get_cookie
    user, proxy, cookies_ = cookies()
  File "C:\Users\YQ\Desktop\小满海关数据爬取\Util\tools.py", line 99, in cookies
    update_cookies()
  File "C:\Users\YQ\Desktop\小满海关数据爬取\Util\tools.py", line 74, in update_cookies
    users[params[0]]['proxy'], users[params[0]]['cookies'] = login(params[0], params[1])
  File "C:\Users\YQ\Desktop\小满海关数据爬取\login1.py", line 81, in login
    return sp.get_login(user, pwd)   #返回cookies
  File "C:\Users\YQ\Desktop\小满海关数据爬取\login1.py", line 54, in get_login
    return self.get_login(user, pwd)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\login1.py", line 69, in get_login
    return self.get_login(user, pwd)
  File "C:\Users\YQ\Desktop\小满海关数据爬取\login1.py", line 24, in get_login
    self.web.get('https://login.xiaoman.cn/login?system_id=discovery&return_url=https%3A%2F%2Fx.xiaoman.cn%2F')
  File "D:\Anaconda\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 332, in get
    self.execute(Command.GET, {'url': url})
  File "D:\Anaconda\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "D:\Anaconda\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: no such session
  (Driver info: chromedriver=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab),platform=Windows NT 10.0.17134 x86_64)

&b792b8d2bb234333-61-EXPORT-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 83, in get_data
    response = self.session.get(url=self.url1, params=params1, proxies={'http': proxy}).json()
  File "D:\Anaconda\lib\site-packages\requests\models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "D:\Anaconda\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "D:\Anaconda\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Anaconda\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
&b792b8d2bb234333-62-EXPORT-Traceback (most recent call last):
  File "C:\Users\YQ\Desktop\小满海关数据爬取\step3.py", line 83, in get_data
    response = self.session.get(url=self.url1, params=params1, proxies={'http': proxy}).json()
  File "D:\Anaconda\lib\site-packages\requests\models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "D:\Anaconda\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "D:\Anaconda\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Anaconda\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
&